services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
#    ports:
#      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_1246
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_1246
      MYSQL_ROOT_PASSWORD: wordpress_124690
#    ports:
#      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_data:/etc/nginx/

volumes:
  wordpress:
  db:
  nginx_data:
