services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: shlink-server
    ports:
      - "8080:8080"
    environment:
      # DEFAULT_DOMAIN: pierceekkman.com
      SHELL_VERBOSITY: 3
      IS_HTTPS_ENABLED: "false"
      GEOLITE_LICENSE_KEY: kjh23ljkbndskj345
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: wordpress_124690
      DB_HOST: 5.161.196.242
      BASE_PATH: /s
      # DB_HOST: db
    restart: always

  shlink-web-client:
    image: shlinkio/shlink-web-client
    container_name: shlink-web-client
    ports:
      - "8089:8080"
    environment:
      - SHLINK_API_URL=http://shlink-server:8080
      - SHLINK_SERVER_API_KEY=9376fe42-2581-47b4-b70d-f3b45af276e5
      - BASE_PATH=/admin
    restart: always

