services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    ports:
      - "8080:8080"
    environment:
      DEFAULT_DOMAIN: pierceekkman.com
      IS_HTTPS_ENABLED: "true"
      GEOLITE_LICENSE_KEY: kjh2335ljkbndskj389
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: 123abc
      DB_HOST: something.rds.amazonaws.com
    restart: always
    networks:
      - shlink_network

networks:
  shlink_network:
    driver: bridge
