services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    ports:
      - "8080:8080"
    environment:
      DEFAULT_DOMAIN: pierceekkman.com
      SHELL_VERBOSITY: 3
      IS_HTTPS_ENABLED: "false"
      GEOLITE_LICENSE_KEY: kjh23ljkbndskj345
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: wordpress_124690
      DB_HOST: 5.161.196.242
      # DB_HOST: db
    restart: always
